### ISSUE TITLE
Error on exporting CA Policies that now include Linux as Preview

### ISSUE THREAD

**Issue by kristinablaze** [dougsbaker/CA-Export#10]
It would be awesome to export our CA policies however I'm running into this error given the preview of using Linux is currently in use:
![image](https://github.com/dougsbaker/CA-Export/assets/93889316/56e3089e-d56b-42d9-97dc-7f1f072b5927)

**Comment by dougsbaker** [comment]
Hi Kristina, please switch to the Graph API module. MSFT has decided to not update the other options.
