### ISSUE TITLE
Get-AzureADMSConditionalAccessPolicy : Error converting value "linux" to type 

### ISSUE THREAD

**Issue by jgriff500** [dougsbaker/CA-Export#2]
Hey Doug,
This looks like a really helpful script.  When I run I get this error. Other errors follow, but they appear to be the affect and not the cause.

Get-AzureADMSConditionalAccessPolicy : Error converting value "linux" to type 'Microsoft.Open.MSGraph.Model.ConditionalAccessDevicePlatforms'. Path 'value[4].conditions.platforms.excludePlatforms[3]', line 1, position 5230.
At line:89 char:17
+     $CAPolicy = Get-AzureADMSConditionalAccessPolicy
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADMSConditionalAccessPolicy], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphV10.Client.ApiException,Microsoft.Open.MSGraphV10.PowerShell.GetAzureADMSConditionalAccessPolicy

Jay

**Comment by jgriff500** [comment]
https://learn.microsoft.com/en-us/answers/questions/768252/get-azureadmsconditionalaccesspolicy-in-a-specific

**Comment by dougsbaker** [comment]
I switched all the options to run with the new Graph Module so it should be working now. I tested with a Linux policy and it looks good now. let me know if you have any issues.
