### ISSUE TITLE
Error converting value "linux" to type 'Microsoft.Open.MSGraph.Model.ConditionalAccessDevicePlatforms'.

### ISSUE THREAD

**Issue by ConradMurrayNB** [dougsbaker/CA-Export#7]
In the Azure Version I get this:

**Get-AzureADMSConditionalAccessPolicy : Error converting value "linux" to type** 'Microsoft.Open.MSGraph.Model.ConditionalAccessDevicePlatforms'. Path 'value[51].conditions.platforms.excludePlatforms[3]', line 1, position 79820.
At C:\Scripts\Export-CaPolicy.v1.ps1:89 char:17
+     $CAPolicy = Get-AzureADMSConditionalAccessPolicy
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADMSConditionalAccessPolicy], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.GetAzureADMSConditionalAccessPolicy

Followed by:
Extracting: CA Policy Data
Converting: AzureAD Guid
Get-AzureADObjectByObjectId : Cannot bind argument to parameter 'ObjectIds' because it is null.
At C:\Scripts\Export-CaPolicy.v1.ps1:194 char:44
+     Get-AzureADObjectByObjectId -ObjectIds $ADsearch |ForEach-Object{
+                                            ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-AzureADObjectByObjectId], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Open.AzureAD16.PowerShell.GetObjectsByObjectIds

Pivoting: CA to Export Format
Get-Member : You must specify an object for the Get-Member cmdlet.
At C:\Scripts\Export-CaPolicy.v1.ps1:237 char:21
+ $Rows = $CAExport | Get-Member | Where-Object {$_.MemberType -eq "Not ...
+                     ~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-Member], InvalidOperationException
    + FullyQualifiedErrorId : NoObjectInGetMember,Microsoft.PowerShell.Commands.GetMemberCommand

**Comment by dougsbaker** [comment]
Switch to the Graph API version. That error is one that I can't fix as it's on the Azure AD module. It's actually one of the reasons I switched to the new version.  When I researched the issue it seems MSFT won't be working to update that module.
